site_name: Linx Blog
site_url: https://blog.linxesp.com
repo_url: https://github.com/Linx-ESP/blog
repo_name: Linx-ESP/blog
theme:
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Cambiar a modo claro

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: ocean-coral
          toggle:
              icon: material/brightness-7
              name: Cambiar a modo oscuro

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: material-ocean
          primary: ocean-coral
          accent: ocean-coral
          toggle:
              icon: material/brightness-4
              name: Usar el modo del sistema

    name: material
    font:
        text: "system-ui" # Defaut Roboto
        code: "JetBrains Mono"
    language: es
    logo: /assets/imagenes/linxtransparenteq100.webp
    favicon: /assets/imagenes/Simplesombratransparente (64px).png
    features:
        - search.suggest
        - search.highlight
        - content.tabs.link
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
        tag:
            cloudflare: fontawesome/brands/cloudflare
            wireguard: simple/wireguard
            tailscale: simple/tailscale
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.tabbed:
          alternate_style: true
    - attr_list
    - md_in_html
    - pymdownx.superfences

plugins:
    - search:
          lang: es

    - rss:
          enabled: true
          date_from_meta:
              as_creation: date
          categories:
              - categories
              - tags
          match_path: posts/.^

    - blog:
          blog_dir: .
          #          pagination_per_page: 1
          enabled: true
          archive: true
          blog_toc: true
          post_date_format: long
          post_url_date_format: yyyy/MM
          # post_url_format: "{date}/{slug}"
          post_readtime: true
          authors: true
          authors_file: .authors.yml
          draft: false
          draft_on_serve: true
          draft_if_future_date: true
    - tags:
          enabled: true
          tags: true
          tags_file: tags.md
    - git-revision-date-localized:
          enable_creation_date: true

extra:
    tags:
        Cloudflare: cloudflare
        WireGuard: wireguard
        Tailscale: tailscale
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Linx-ESP
